version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 18000:8000 # 호스트 머신의 18000번 포트를 docker의 8000번 포트에 연결
    environment:
      - WATCHFILES_FORCE_POLLING=true #환경에 따라 핫 리로드를 위해 필요함
  db:
    image: mysql:8.0
    platform: linux/x86_64 # 애플 실리콘 맥(m1/m2 등)의 경우 필요
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass
      MYSQL_DATABASE: demo # demo 데이터베이스를 초기 데이터 베이스로 설정
      TZ: Asia/Seoul # 시간대를 한국 시간대로 서정
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # MYSQL 8.0 에서는 기본값이 "caching_sha2_password" 이라 드라이버가 비지원이므로 변경
    ports:
      - 33306:3306 # 호스트 머신의 33306번 포트를 docker의 3306번 포트로 연결
volumes:
  mysql_data: