version : '3'
services :
  demo-app :
    build : .
    volumes :
    - .dockervenv:/src/.venv
    - .:/src
    ports :
      - 18000:8000 # 호스트 머신의 18000번 포트를 docker의 8000번 포트에 연결
    environment:
      - WATCHFILES_FORCE_POLLING=true #환경에 따라 핫 리로드를 위해 필요함
